=== l7bibe/RLSTROR/schema/notifications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="notifications">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="notification" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="message" type="xs:string"/>
                            <xs:element name="time" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== l7bibe/RLSTROR/data/notifications.xml
<?xml version="1.0" encoding="UTF-8"?>
<notifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/notifications.xsd">
    <notification id="1">
        <type>info</type>
        <message>XML System Sync Initiated</message>
        <time>Just now</time>
    </notification>
    <notification id="2">
        <type>warning</type>
        <message>Low Stock Alert: LED Bulb</message>
        <time>5m ago</time>
    </notification>
</notifications>
