=== l7bibe/RLSTROR/schema/system_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="systemConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="currentUser">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="role" type="xs:string"/>
                            <xs:element name="avatar" type="xs:anyURI"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="appSettings">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="itemsPerPage" type="xs:integer"/>
                            <xs:element name="theme" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== l7bibe/RLSTROR/data/system_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<systemConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/system_config.xsd">
    <currentUser>
        <name>Admin</name>
        <role>Senior Administrator</role>
        <avatar>https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&amp;auto=format&amp;fit=crop</avatar>
    </currentUser>
    <appSettings>
        <itemsPerPage>8</itemsPerPage>
        <theme>dark</theme>
    </appSettings>
</systemConfig>
